services:
  - type: web
    name: tribike
    runtime: php
    buildCommand: ""
    startCommand: php -S 0.0.0.0:$PORT
    envVars:
      - key: PHP_VERSION
        value: 8.1
    healthCheckPath: /index.php

databases:
  - name: tribike-db
    databaseName: tribike
    user: tribike_user
    plan: free

